server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          # 서비스 디스커버리 기능 활성화
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true   # 서비스 ID를 소문자로 사용
          httpclient:
            response-timeout: 5000
            # 연결 타임아웃 (다운스트림 서비스와 연결을 맺는 시간)
            connect-timeout: 1000
          default-filters:
            - AuthenticationFilter
          routes:
            - id: member-service-route
              uri: lb://member-service
              predicates:
                - Path=/api/v1/members/**
            - id: product-service-route
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/products/**
              filters:
                - name: Retry
                  args:
                    retries: 3
                    statuses:
                      - BAD_GATEWAY           # 502
                      - SERVICE_UNAVAILABLE   # 503
                      - GATEWAY_TIMEOUT       # 504
                    methods:
                      - GET
                    backoff:
                      firstBackOff: 100ms
                      maxBackOff: 500ms
                      factor: 2
                      basedOnPreviousValue: true
            - id: order-service-route
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/orders/**
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 15s
        instance-id: ${spring.application.name}:${random.value}

# Actuator의 health 엔드포인트 활성화
management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: 'a_very_long_and_secure_secret_key_for_ecommerce_project_that_is_at_least_256_bits_long' #

security:
  required-roles:
    - path: /api/v1/admin/**
      role: ADMIN
    - path: /api/v1/orders/**
      role: USER
