server:
  port: 8081

spring:
  application:
    name: member-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ecommerce
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 15s
        instance-id: ${spring.application.name}:${random.value}


# Actuator의 health 엔드포인트 활성화
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/    # Eureka 서버 주소
#  instance:
#    prefer-ip-address: true   # IP 주소로 등록되도록 설정

member:
  greeting: "Ciao, Member!"